---
platforms:
  - name: borg-server-ubuntu-24
    groups:
      - ubuntu
    image: "docker.io/geerlingguy/docker-ubuntu2404-ansible"
    override_command: false
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true

  - name: borg-server-ubuntu-22
    groups:
      - ubuntu
    image: "docker.io/geerlingguy/docker-ubuntu2204-ansible"
    override_command: false
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true

  - name: borg-server-debian-13
    groups:
      - debian
    image: "docker.io/geerlingguy/docker-debian13-ansible"
    override_command: false
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true

  - name: borg-server-debian-12
    groups:
      - debian
    image: "docker.io/geerlingguy/docker-debian12-ansible"
    override_command: false
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true

  - name: borg-server-debian-11
    groups:
      - debian
    image: "docker.io/geerlingguy/docker-debian11-ansible"
    override_command: false
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
